### ISSUE TITLE
Playing Team Radio softlocks

### ISSUE THREAD

**Issue by Chronophylos** [JustAman62/undercut-f1#25]
After the audio finishes my cursor is displayed in the top left corner and input do not register anymore. The only way to exit is C-c.

**Comment by deanc** [comment]
Team radio does nothing for me on MacOS when pressing enter (running inside a container).  Clicking [T] to transcribe also does nothing (presumably due to missing whisper setup - but it should maybe check for that at launch) - but it also causes 100% CPU.

**Comment by Chronophylos** [comment]
100% might be caused because the ML Model is running on the CPU.

**Comment by deanc** [comment]
@Chronophylos In my case I don't _have_ whisper, so it's certainly not the model running that's causing 100% CPU

**Comment by Chronophylos** [comment]
The model gets downloaded when you attempt to transcribe the audio see https://github.com/JustAman62/undercut-f1/blob/master/UndercutF1.Data/TranscriptionProvider.cs#L54

**Comment by evulhotdog** [comment]
I was able to get the audio to transcribed (even if inaccurate) and the audio to play on the previous version. With the current version, audio no longer plays (it doesn't show the "stop" like it did before when you start it, so I think it's actually starting.)

**Comment by JustAman62** [comment]
Yep, I managed to break the input handling of the Enter key in the last release :( I've merged #27 now to fix that issue, so audio playback should work when I make another release.

Interesting that the playback bricks your terminal, what OS and Terminal are you using? I'll try to replicate.

In terms of the Whisper stuff, to be totally honest I basically got that to accidentally work a long time ago and haven't gone back to clean up all the implementation around that. I'll try to clean it up and improve the UI feedback sometime this week.

**Comment by stendarr** [comment]
I'm able to transcribe the radio messages but I'm unable to play them. Hitting enter doesn't break or softlock anything, it just doesn't play anything. Are the radio messages downloaded and if yes, where? I wanted to check if I can play them with another player but couldn't find the files. (Currently running debian trixie as my OS with kernel version 6.12.21.)

**Comment by JustAman62** [comment]
> I'm able to transcribe the radio messages but I'm unable to play them. Hitting enter doesn't break or softlock anything, it just doesn't play anything. Are the radio messages downloaded and if yes, where? I wanted to check if I can play them with another player but couldn't find the files. (Currently running debian trixie as my OS with kernel version 6.12.21.)

I've released [https://github.com/JustAman62/undercut-f1/releases/tag/v3.0.31](v3.0.31) which should resolve this issue. The Enter key wasn't being handled correctly meaning the messages weren't being played.

Team radio playing/transcription still won't be working if you're running using Docker though.

The radio messages are downloaded on demand (when you press Play or Transcribe), however they're downloaded to the /tmp directory with a random filename. I'm using dotnets `Path.GetTempFileName()` API for this file path.

**Comment by stendarr** [comment]
I have found out why it doesn't work for me, it looks like it's invoking `/bin/bash mpg123` to play the files even though other players are available, but just installing mpg123 was enough to make it work for me.

**Comment by Chronophylos** [comment]
> Interesting that the playback bricks your terminal, what OS and Terminal are you using? I'll try to replicate.

I am using Linux and kitty.

I tried the newest version `3.0.31` and the bug still occurs.

![Image](https://github.com/user-attachments/assets/dd942fe3-2b18-40a7-921a-910237a5fe33)

**Comment by JustAman62** [comment]
> > Interesting that the playback bricks your terminal, what OS and Terminal are you using? I'll try to replicate.
> 
> I am using Linux and kitty.
> 
> I tried the newest version `3.0.31` and the bug still occurs.
> 
> ![Image](https://github.com/user-attachments/assets/dd942fe3-2b18-40a7-921a-910237a5fe33)

Hmm, still unable to replicate (however I am running Linux via Docker, so not representative). The escape code that is printed there is for the Up Arrow, I have no explanation for why that would print and then soft lock. 

Do you have anything in logs (currently logs should be in `~/undercut-f1/logs`) related to this? The terminal should be in raw mode with the cursor off, so that fact you have a cursor and are seeing printed output means something has gone pretty wrong and caused it to exit I think.

Also, as you are on Linux, do you have `mpg123` installed in by your distro? (If so, can you paste the output of `mpg123 --version; which mpg123`?). If you do not, can you try installing `mpg123` and seeing if it works? The NetCoreAudio library I am using will try to execute `/bin/bash -c mpg123 <filename>` (as described by stendarr above), so if this command fails in an unexpected way, that could be the cause of the soft lock. When `mpg123` is missing it normally fails gracefully though.

**Comment by Chronophylos** [comment]
I don't see anything wrong in the logs.

<details>
<summary>cat ~/undercut-f1/logs/undercutf12025042211.log</summary>

```
2025-04-22 11:42:58.350 +02:00 [INF] Application started. Press Ctrl+C to shut down.
2025-04-22 11:42:58.372 +02:00 [INF] Hosting environment: Production
2025-04-22 11:42:58.373 +02:00 [INF] Content root path: /home/chrono
2025-04-22 11:43:03.009 +02:00 [INF] Starting Live Timing client
2025-04-22 11:43:03.584 +02:00 [INF] Subscribing
2025-04-22 11:43:03.712 +02:00 [INF] Found session key from subscription data: 2025_Jeddah_Race
2025-04-22 11:43:03.712 +02:00 [WRN] Data Subscription file already exists, will not create a new one
2025-04-22 11:43:03.713 +02:00 [INF] Handling subscription data
2025-04-22 11:43:03.778 +02:00 [INF] Loading circuit data for key 149
2025-04-22 11:43:03.841 +02:00 [INF] Started Live Timing client
2025-04-22 11:43:46.380 +02:00 [INF] Application is shutting down...
2025-04-22 11:43:46.383 +02:00 [INF] ConsoleLoop Stopping.
2025-04-22 11:43:46.427 +02:00 [WRN] Live timing client connection closed, attempting to reconnect
2025-04-22 11:44:04.556 +02:00 [INF] Application started. Press Ctrl+C to shut down.
2025-04-22 11:44:04.578 +02:00 [INF] Hosting environment: Production
2025-04-22 11:44:04.579 +02:00 [INF] Content root path: /home/chrono
2025-04-22 11:44:05.691 +02:00 [INF] Starting Live Timing client
2025-04-22 11:44:06.230 +02:00 [INF] Subscribing
2025-04-22 11:44:06.361 +02:00 [INF] Found session key from subscription data: 2025_Jeddah_Race
2025-04-22 11:44:06.361 +02:00 [WRN] Data Subscription file already exists, will not create a new one
2025-04-22 11:44:06.361 +02:00 [INF] Handling subscription data
2025-04-22 11:44:06.426 +02:00 [INF] Loading circuit data for key 149
2025-04-22 11:44:06.489 +02:00 [INF] Started Live Timing client
2025-04-22 11:51:17.002 +02:00 [INF] Application is shutting down...
2025-04-22 11:51:17.005 +02:00 [INF] ConsoleLoop Stopping.
2025-04-22 11:51:17.191 +02:00 [WRN] Live timing client connection closed, attempting to reconnect
```
</details>

<details>
<summary>mpg123 --version; which mpg123</summary>

```
mpg123 1.32.10
/usr/bin/mpg123
```
</details>

**Comment by JustAman62** [comment]
In [v3.1.63](https://github.com/JustAman62/undercut-f1/releases/tag/v3.1.63) I've written my own audio playback implementation so that I can control the execution better. Now the terminal should not be corrupted when playing back Team Radio using `mpg123`. There is also [a new `preferFfmpegPlayback` configuration](https://github.com/JustAman62/undercut-f1?tab=readme-ov-file#configuration) option that lets you choose `ffplay` as the playback executable instead of the default for your OS.

Let me know if you still face playback issues after this release.

**Comment by Chronophylos** [comment]
It seems to work for me without problems!

Thank you for your work :)
